// Get All Suppliers
export const ALL_SUPPLIER_REQUEST = "ALL_SUPPLIER_REQUEST";
export const ALL_SUPPLIER_SUCCESS = "ALL_SUPPLIER_SUCCESS";
export const ALL_SUPPLIER_FAIL = "ALL_SUPPLIER_FAIL";

// Get Supplier Details
export const SUPPLIER_DETAILS_REQUEST = "SUPPLIER_DETAILS_REQUEST";
export const SUPPLIER_DETAILS_SUCCESS = "SUPPLIER_DETAILS_SUCCESS";
export const SUPPLIER_DETAILS_FAIL = "SUPPLIER_DETAILS_FAIL";
export const SUPPLIER_DETAILS_RESET = "SUPPLIER_DETAILS_RESET"; // Add this line

// Admin Supplier Operations
export const ADMIN_SUPPLIER_REQUEST = "ADMIN_SUPPLIER_REQUEST";
export const ADMIN_SUPPLIER_SUCCESS = "ADMIN_SUPPLIER_SUCCESS";
export const ADMIN_SUPPLIER_FAIL = "ADMIN_SUPPLIER_FAIL";

// Create New Supplier
export const NEW_SUPPLIER_REQUEST = "NEW_SUPPLIER_REQUEST";
export const NEW_SUPPLIER_SUCCESS = "NEW_SUPPLIER_SUCCESS";
export const NEW_SUPPLIER_FAIL = "NEW_SUPPLIER_FAIL";
export const NEW_SUPPLIER_RESET = "NEW_SUPPLIER_RESET";

// Delete Supplier
export const DELETE_SUPPLIER_REQUEST = "DELETE_SUPPLIER_REQUEST";
export const DELETE_SUPPLIER_SUCCESS = "DELETE_SUPPLIER_SUCCESS";
export const DELETE_SUPPLIER_FAIL = "DELETE_SUPPLIER_FAIL";
export const DELETE_SUPPLIER_RESET = "DELETE_SUPPLIER_RESET";

// Update Supplier
export const UPDATE_SUPPLIER_REQUEST = "UPDATE_SUPPLIER_REQUEST";
export const UPDATE_SUPPLIER_SUCCESS = "UPDATE_SUPPLIER_SUCCESS";
export const UPDATE_SUPPLIER_FAIL = "UPDATE_SUPPLIER_FAIL";
export const UPDATE_SUPPLIER_RESET = "UPDATE_SUPPLIER_RESET";

// Clear Errors
export const CLEAR_ERRORS = "CLEAR_ERRORS";
